<?php
$graph_api_server = 'http://ser3.graphmovie.com/gmspanel/interface/zh-cn/3.1_test/';
return array(
	'POST_API' => array(
		'adv_comment' => $graph_api_server.'A_AdvSendComment.php', // 广告发表评论接口
		'movie_comment' => $graph_api_server.'M_MvSendComment.php', // 电影发表评论接口
		'movie_rank_pre' => 'http://127.0.0.1/gmspanel/controlboard/set_movie_rank.php', // 电影预评级接口
		'upload_img_serv' => 'http://imgs5.graphmovie.com/graphmovie/up.php', // 上传图片服务器接口
		'get_script_img_size' => '/graphmovie/get_size.php', // 获取脚本图片所在服务器图片信息
		'get_script_img_info' => '/graphmovie/get_img_info.php' // 获取图片所在服务器图片的信息（大小，宽高等）
	),
	'GET_API' => array(
		'create_rss' => 'http://127.0.0.1/gmspanel/rss/creat_rss.php',
		'movie_read_behavior' => 'http://ser3.graphmovie.com/boo/interface/api/server/Movie_Read_Behavior.api.php'
	),
	'API_LAN_NAME' => array(
		'A_AdvCommentAlert' => '举报广告评论',
		'A_AdvCommentOO' => '顶广告评论',
		'A_AdvComments' => '广告评论列表',
		'A_AdvCommentXX' => '踩广告评论',
		'A_AdvSendComment' => '发广告评论',
		'A_AdvSendPoptxt' => '发广告弹幕',
		'A_AdvUserCai' => '踩广告',
		'A_AdvUserDing' => '顶广告',
		'A_AdvUserKeep' => '收藏广告',
		'A_AdvUserShare' => '分享广告',
		'A_AdvVolPoptxt' => '广告弹幕列表',
		'A_AdvVolScript' => '广告解说',
		'A_MainAdvList' => '广告列表',
		'M_HotTagMvList' => '标签点击',
		'M_MainMvList' => '影片列表',
		'M_MvCommentAlert' => '举报影片评论',
		'M_MvCommentOO' => '顶影片评论',
		'M_MvComments' => '影片评论列表',
		'M_MvCommentXX' => '踩影片评论',
		'M_MvDetails' => '影片剧集',
		'M_MvGuessLike' => '猜你喜欢',
		'M_MvRelateTo' => '相关推荐',
		'M_MvReportReaddata' => '上报数据',
		'M_MvSendComment' => '发影片评论',
		'M_MvSendPoptxt' => '发影片弹幕',
		'M_MvTagCount' => '影片筛选',
		'M_MvUserCai' => '踩影片',
		'M_MvUserDing' => '顶影片',
		'M_MvUserKeep' => '收藏影片',
		'M_MvUserShare' => '分享影片',
		'M_MvVolPoptxt' => '影片弹幕列表',
		'M_MvVolScript' => '影片解说',
		'M_SyncMvMsgList' => '修复影片',
		'S_SearchKeyword' => '搜索',
		'S_SerHotTag' => '热门标签列表',
		'T_TopicList' => '专辑列表',
		'T_TopicMovies' => '专辑影片',
		'UM_BindSns' => '绑定SNS',
		'UM_ChangeUserMsg' => '修改头像名称',
		'UM_ChangeUserName' => '修改名称',
		'UM_CkUser' => '检查用户信息',
		'UM_CkUserNews' => '用户动态',
		'UM_EmailLogin' => '邮箱登陆',
		'UM_EmailSignin' => '邮箱注册',
		'UM_GrapherList' => '排行榜',
		'UM_GrapherWorks' => '个人作品列表',
		'UM_SendNewsReply' => '回复动态',
		'UM_SendUserComment' => '发用户留言',
		'UM_SnsSignin' => '第三方注册',
		'UM_ToUserComments' => '留言板信息',
		'UM_UserCommentAlert' => '举报留言板',
		'UM_UserCommentOO' => '顶留言板',
		'UM_UserCommentXX' => '踩留言板',
		'UM_UserFeedback' => '用户反馈',
		'UM_UserLikeUser' => '喜欢用户',
		'W_SendWantSee' => '发送求片儿',
		'W_WantSeeList' => '求片儿榜单',
		'webui' => 'web阅读解说'
	)
);
